### ISSUE TITLE
Cross referencing Resources

### ISSUE THREAD

**Issue by duglin** [xregistry/spec#112]
Do we want to support the idea of one Resource being part of more than one Group? Basically define a Group to include some kind of $ref that's a URL to a Resource in some other group (or even xRegistry) as a way to include it in this other group?
If so, how will filtering work?

@deissnerk do I have this right?

**Comment by duglin** [comment]
Briefly discussed this on the 4/7 call and SAP will try to come up with the start of a proposal. However, we did agree that any solution will probably be additive to the spec, so it's probably not a blocker for v1

**Comment by duglin** [comment]
On our call yesterday @clemensv mentioned that he does want to have xReg support Resources being part of more than one Group for v1. Let's use this issue to discuss this requirement while SAP works on their usecase.

Some design questions I have:
- is it ok that the Resource that is shared will have one Group as its "primary" parent as denoted by the Group ID in its "self" URL?
- Will the "self" URL ever change based on how the Resource is found? For example, as someone traverses from a Group into one of these cross-referenced Resources via the RESOURCEs collection, is it ok that the URL of (what appears to be) a child Resource doesn't have the same base URL as its Group or its sibling Resources? Alternatively, should the Resource's URLs appear to be for the secondary Group, but have an attribute to indicate where the Resource is really from - e.g. the other Group - basically something similar to the "origin" attribute. Also see question below about how it "appears".
- At a high level, I think the main question is... should clients be aware of this cross referencing or should it all be hidden by the server? 
- what happens if the primary Group is deleted? Does the Resource vanish from other Groups? Does its "primary" parent change? And if so, to which Group?
- Should people be allowed to filter based on Resources that are available via these cross-references?
- How does a Resource appear under more than one Group? For example, let's assume the "primary" Group shows the Resource as it does today - under its RESOURCEs collection. When that Resource appears as part of a second Group does it appear the exact same way (just as a RESOURCEs child), or does the RESOURCEs child entity act as a placeholder Resource and include some kind of "redirect" attribute? Sort of like a 3xx response code in HTTP.
- can we cross reference across xRegistries?

**Comment by Fannon** [comment]
Writeup of some ideas from our meeting on 2024-07-06

* I personally would distinguish between a merge semantics (like $ref in JSON Schema) and a regular association. The latter doesn't imply that data should be merged together, just that there's a relationship to the target and that the link can be followed / looked up. 
* If we have associations / references, we may have different kinds of IDs: 
  * xRegistry internal IDs: Those IDs can be looked up within the xRegistry itself (like self today?). They are unique within the current xRegistry, but not necessarily globally
  * Klaus mentioned that there can also be IDs that have already been defined externally (like `id` in JSON Schema). There might be cases where we want to be able to look those up as well ? If yes, it might need a dedicated API operation for such lookups. 
  * Some links are going external, maybe just URLs. We should not expect the xRegistry server to be able to actually resolve them or understand what's behind those URLs. 
  * Maybe references across xRegistries are a special case of external linsk / URLs. If we know that the URL points to an xRegistry server (we could do a #120 well-known lookup to verify that), we may treat those IDs specially as we know we can rely on the xRegistry protocol on how to look things up. 

If we want associations, there are a few steps how we can get there, many of them optional:
* Mandatory: The xRegistry meta model needs to be able to describe that something is an association and what "type" of association it is. E.g. is it an internal URL or not. Cardinality. Maybe if referential integrity is important or not (with eventual consistency). With that, we at least document that this is not just a string or an URL, it's something a consumer can look up and follow.
* Optional: We could have smart clients who understand from the meta-model what's an association and do inlining / follow up / lookup / filter dynamically by doing multiple requests in the background
* Optional: The xRegistry server API could support inlining, filtering etc. with associations as well, but at that point we'll build a generic protocol much like GraphQL or OData. 

Regarding the problem of multiple groups: We could have custom defined groups as a resource type and use associations to assign resources to multiple groups. The xRegistry is then also extensible on what kind of groups there could be in the first place. 

Another note: If we have xRegistry internal IDs, they would **not** be the current `id` property, but something more like `self`. That may be a bit confusing.

**Comment by Fannon** [comment]
Maybe one question is also if the group should be part of a resources ID. If you use it like a namespace, this may be really what you want. If the ID of a resource shouldn't change depending of the group assignment(s), then it may be better to have resource as a top-level concept and treat groups as a (special) kind of resource.

**Comment by deissnerk** [comment]
I would distinguish groups that **own** a resource and groups that are more like a categorization or tag. The owners would be relevant for the resource's lifecycle, and their `id` could be seen as a namespace for the resource's `id`.

**Comment by duglin** [comment]
If a Resource can be part of more than one group, what if one Groups references multiple Resources but those Resources have the same `id`? Are they just out of luck and can't do it? Do we want to support the ability to change the `id` of a referenced Resource?

**Comment by Fannon** [comment]
For xRegistry internal associations / references, we could use the URN concept, no need to have full URLs. 

E.g. AWS does this with their ARNs. Such URNs are ideally self contained and after parsing contain all information that we need to do a lookup and know what we'll get. 

Examples:
* `schemagroups:productX:schemas:eventA:v1` for the most exact ID, including pointing out which version
* `schemagroups:productX:schemas:eventA:` Would point to the default version 
* `schemagroups:productX:::` would point to ProductX itself.

**Comment by duglin** [comment]
Proposal:
- define a new Resource attribute called `xref`. Note it can only appear in a Resource, not a Version
- xref's value MUST be a URL - relative or absolute. Can point to a Resource in another Registry
  **- Q: when are fragement URLs used?**
- when `xref` appears in a Resource, it MUST be the only "native" attribute listed aside from `id`. If others appear in its serialization, it is because they are inlined from the target Resource (see below)
- its `id` MAY be different from the `id` of the target Resource
- **when the URL is relative, both source and target Resource type models MUST be the same and under the same Group type**
- when present on a write operation request, all other attributes (except `id`) MUST be ignored (and in the case of converting a normal Resource into a reference, existing attributes are deleted - except `id`). This includes ignoring the `?nested` flag
- a write operation request that directly or implicitly clears the `xref` attribute removes the pointer
- when present on a read operation response, the target Resource's attributes SHOULD be inlined unless the URL is absolute (not in same Registry), or the `export` flag it used. `xreg` MUST still appear after the inlining
**- if the target Resource itself has an `xref`, then no inlining is done and the 2nd xref is not followed**
- note that inlining will pull in a target Resource Versions too

- define an `export` flag (or `doc`?) to ask for a compact view
  - no filtering allowed
  - `?inline=*` is implied
  - can be rooted at any level of the hierarchy
  - Resources MUST NOT have default Version attributes shown, source of truth is in the `versions` collection
  - Resources with `xref` MUST NOT have target Resource inlined

**Comment by Fannon** [comment]
> xref's value MUST be a relative URL from the root of the registry. Whether it is /... or ... is an impl detail.

I think it would be great if we clearly standardize this, so there's just one way how to create this. Essentially, I see it as the true ID for references within the xRegistry. It would be nice if this ID would also always be automatically be added to the responses, so you know how to look something up or how to refer to it.

> "$import": [ "endpoints/definitions", "messagegroups/messages" ]

Here I have an issue in my understanding. How would this import result in the meta model? Would it create a new attribute with the singular or plural name of the imported resource? 
My concern here is that we cannot freely choose the attribute name of the import or that we cannot decide whether something can have a single include or multiple includes. For example, one server could have import of 0..n endpoints. But one event message only has an import of 0..1 schema.

**Comment by deissnerk** [comment]
@Fannon 
> My concern here is that we cannot freely choose the attribute name of the import or that we cannot decide whether something can have a single include or multiple includes. For example, one server could have import of 0..n endpoints.

I think @duglin 's proposal refers only to the case where the same resource type is used in different groups or registries. It is only meant to occur in the `/model/groups/GROUPs/resources` object of a group. The use case of re-using a schema resource from within a `message` resource to cover inlining of a schema is not covered.

**Comment by duglin** [comment]
> >  xref's value MUST be a relative URL from the root of the registry. Whether it is /... or ... is an impl detail.
> 
> I think it would be great if we clearly standardize this, so there's just one way how to create this. Essentially, I see it as the true ID for references within the xRegistry. It would be nice if this ID would also always be automatically be added to the responses, so you know how to look something up or how to refer to it.

If we were to standardize this then I think it makes most sense to mandate:
- it be a relative URL from the "base URL" of the registry
- it MUST NOT start with "/" as to avoid confusion when the base URL is more than just a hostname
- the base URL is assumed to end with a "/" even if not explicit to avoid confusion when combining with the xref URL (meaning, when do we remove the last word of the base URL vs keep it?) E.g. base: http://example.com/myreg   + xref: groups/g1/resources/r1  - is the result: http://example.com/myreg/groups/g1/resources/r1 or is it http://example.com/groups/g1/resources/r1 ?  We want the former.

Would that work?

**Comment by Fannon** [comment]
yes, that looks good! If we automatically include this ID (maybe as `xid` as they can be used for `xref`s ?), then those rules don't even need to be understood by end-users. The xRegistry will generate them correctly and you just use them.
