### ISSUE TITLE
Should deleting a Version update a Resource's epoch value?

### ISSUE THREAD

**Issue by duglin** [xregistry/spec#178]
pros:
- a change was made so it makes sense to do so

cons:
- if a client is looping over a set of versions to delete them, then the 2nd+ DELETE might value due to the epoch values changing. They would need to refresh (re-GET) each version prior to doing a DELETE. Very annoying.

Note that creating a new version does update the epoch value... at least in my impl. Should it?

Same for setting default version id.

Same is true for a loop to update Versions... will need to refresh all Versions after each update prior to the 2nd+ update.

Overall, this issue comes down to two things:
1 - when does a Resource's epoch value get updated?
- When a resource level property is updated?
- When a version level property is updated?
- When a version is added?
- When a version is deleted?

2 - is it ok for a user to have to re-GET version(s) due to the Resource's epoch value changing?
- e.g. iterating thru the Versions (adding or removing) will invalidate all cached versions causing the user to have to re-GET all of them. Pretty annoying.

**Comment by duglin** [comment]
Proposal: no. Let's treat the "verisons" collection and the "versionscount" attributes as special (calculated) values, which means adding/deleting versions MUST NOT update the Resource's "epoch" value. Having to re-GET a Resource if someone else adds/removes a version provides no real value to clients as there isnt' any data inconsistency or potential overwrite issue to worry about.

A Resource's epoch value will only change when any "client editable" Resource level property changes.

**Comment by duglin** [comment]
This proposal breaks for the "touch" semantics currently in the spec... more thinking is needed

**Comment by duglin** [comment]
e.g.
```
PUT /

{
  "endpoints": {
    "e1": {
      "messages": {
        "m1": {
          "versions": {
            "v5": { ... }
          }
        }
      }
    }
  }
}
```

Proposal:
- touch only applies to the lower-level (leaf) of the request data. So, in the above example we touch/update/create v5 because it's a leaf of the request.
- if they want to touch something higher in the tree too, then add some attribute even if unchanged to that level.

**Comment by duglin** [comment]
Proposal:
- deleting an entity from an xRegistry collection DOES NOT modify the parent's epoch or modifiedat timestamp. Note that modifying a user-defined map/object/array MUST do it though
- PUT/POST/PATCH directed to an entity MUST always modify the entity's epoch/modifiedat even if no attributes are specified (even for PATCH) and even if the only reason the entity is there is to access a child collection. E.g. `PATCH GROUPS/gID/RESOURCES` +
```
{
  "rID1": {
    "versions": {
      "v1": ...
    "
  },
  "rID2": {
    "versions": {
      "v2": ...
    "
  }
}
```

**Comment by manuelottlik** [comment]
I think there is a use case for a consumer to fetch a resource and check the epoch level to find out if anything has changed. If the epoch value does not update when versions of that resource are created or deleted, how can that use case be fulfilled otherwise?

**Comment by duglin** [comment]
Proposal:
copy what filesystems do - meaning:
- adding/removing children changes epoch + timestamp
- attribute level changes in a child do not result in changing the parent's epoch+timestamp attributes

agreed to do this on the 12/3 call
