### ISSUE TITLE
?inline=* will show the model, but should it be special?

### ISSUE THREAD

**Issue by duglin** [xregistry/spec#186]
Now that ?model is gone and we treat it like all other inlinable sub-objects, `?inline=*` will inline/show all inlinable entities (model, groups, resources, resource docs, meta). However, "model" is different because it's not really "user data" as much as it's "the metadata describing the user data". As such, a normal user might not really want to see pages and pages of JSON for the model when they do "GET /?inline=*". It'll just feel like noise. Granted, this is only really an issue when they print the response - when in code they can just ignore that attribute.

However, should we do something special with "model"? Some options:
1 - no, treat it like all others and if they want to exclude it then they need to `?inline` just the ones they want - e.g. `?inline=endpoints.messages.versions,endpoints.messages.meta` for the endpoint registry
2 - allow `?inline=*` to pull in everything except "model". To include model they would need to explicitly mention it: `?inline=model,*`
3 - allow for exclusions - e.g.: `?inline=*&inline=-model`
4 - allow for the `*` to be more like a wildcard and allow it to mean "everything from this level down". E.g. `?inline=endpoints.*` means everything under `endpoints`, so `messages, messages.version, messages.meta`. An easier option 1. Note that `?inline=*` still has the exact same semantics.

Proposal: do 2 and 4
This will allow `?inline=*` to do what I think most people want (everything except "model") by default, but allow for an easy way to also include "model" with just a few more characters. I want to include 4 (even though it's technically a different issue/solution) because it just feels like a really nice UX feature to add while we're looking at this feature. But I'm ok with leaving option 4 out of the spec for now and adding it later if people are uncomfortable with it at this time.

**Comment by clemensv** [comment]
The model is, for the most part, an internal implementation detail of the registry. The end-users will have the JSON schema and the OpenAPI contract that inform their interactions and contain the realized model for the respective registry. Therefore it's more confusing than it helps to show the model unless someone specifically asks for it.

**Comment by duglin** [comment]
What is your preferred solution?
