### ISSUE TITLE
Do we want a new optional "mustunderstand" core attribute?

### ISSUE THREAD

**Issue by jskeet** [xregistry/spec#194]
Extensions such as #1317 are much more useful if there's some guarantee that consumers will honor them.

We could introduce a new attribute of "mustunderstand" that lists the extensions that a consumer must understand in order to process the message further.
I don't know how this would be played out in SDKs, and it could be tricky to add within v1. But let's discuss.

**Comment by duglin** [comment]
Closing, wrong repo - created https://github.com/cloudevents/spec/issues/1321 for it.
