### ISSUE TITLE
Inconsistent CloudEvent definitions?

### ISSUE THREAD

**Issue by matzew** [xregistry/spec#39]
Looking at https://github.com/xregistry/spec/blob/main/message/spec.md#cloudevents10

I see that the CE required `specversion` is implied by the format (e.g. CloudEvents/1.0), and hence is optional on the metadata/attributes".

However, isn't the same true for the  "metadata/attributes", which matches the `ID` of the message definition itself?

**Comment by duglin** [comment]
I'm not 100% sure I'm following the question so let me know if I'm off, but the `ID` of a message isn't the same as the `id` of a CE. The CE `id` will be unique per CE/message instance, while the`ID` of the message is static and more like a definition-time property, while CE `id` is more like a runtime-property. Does that help?


A related question, later on in that section it says: `For clarity of the definition, you MAY always declare all implied attribute properties explicitly, but they MUST conform with the rules above.`, but that isn't true for `specversion` per the text you mentioned. I wonder if, from a consistency perspective, we should include `specversion` too. WDYT?

It's also not clear to me why `id` isn't part of the "metadata/attributes" when other attributes (like "subject") are. Ping @clemensv

**Comment by duglin** [comment]
Closing as we think the rewrite of the spec may have addressed this. Let us know if it didn't and we can reopen.
