### ISSUE TITLE
xReg: de-normalize our data model?

### ISSUE THREAD

**Issue by duglin** [xregistry/spec#4]
from @deissnerk
See: https://github.com/cloudevents/spec/pull/624/files#r427115684

@deissnerk would you like to write-up a rough idea of what you think the changes to the spec would be?

Klaus wrote:
This depends on what we want to achieve with discovery. Is the discovery API only used to support UIs for browsing events? Do people have in mind to generate boiler plate coding for event handling and generation based on the descriptions in discovery? Will there be some kind of document format to describe a set of events and services? This could be needed for registering a producer with an intermediary. The drafts for subscription and discovery are important pieces in the puzzle, but the overall picture is not yet clear to me. Perhaps we should work on a primer for these topics first.
Btw. https://github.com/cloudevents/spec/issues/635 is also related to this.

Moved from: https://github.com/cloudevents/spec/issues/630

**Comment by duglin** [comment]
@deissnerk do you think this issue is still valid?

**Comment by deissnerk** [comment]
@duglin I think you can close it. Our model has changed significantly since we had the discussion that triggered this issue.
