### ISSUE TITLE
Potentially new xRegistry logo

### ISSUE THREAD

**Issue by duglin** [xregistry/spec#40]
See some ideas from the CNCF design team: https://drive.google.com/file/d/1rSZsnU6xQQC99P8owQUxXpsdY6DqoEUS/view?usp=sharing

Today's:
![image](https://github.com/xregistry/spec/assets/1944671/ba3c0ceb-37b8-433b-93df-6a23ef49ff71)

**Comment by duglin** [comment]
Next version: https://drive.google.com/file/d/1C5TSybZqS3_lW3unWPen3RKCYmYI78oB/view?usp=drive_link

**Comment by deissnerk** [comment]
I also liked Option 5 and 6 of the first set of designs. 😄

**Comment by duglin** [comment]
New proposed logos: https://drive.google.com/file/d/1w3rOAYfgDpRkDvjVc6PI4gFQPF0jRx-y/view?usp=drive_link

**Comment by duglin** [comment]
Per @markpeek's suggestion - we're going to start a vote by adding each proposed logo as a new comment. Please vote for the ONE you like the best. Hoping to end the vote during our next call.... Jan 11, 2024

**Comment by duglin** [comment]
Option 1:
<img width="345" alt="image" src="https://github.com/xregistry/spec/assets/1944671/ca887742-8907-4ba7-8d1e-96dcc04f2b49">

**Comment by duglin** [comment]
Option 2:
<img width="350" alt="image" src="https://github.com/xregistry/spec/assets/1944671/dafd031b-3475-46a7-b009-21d307614df0">

**Comment by duglin** [comment]
Option 3:
<img width="351" alt="image" src="https://github.com/xregistry/spec/assets/1944671/dccea92b-a9ca-414d-8ef6-ef21387b032a">

**Comment by duglin** [comment]
Option 4:
<img width="337" alt="image" src="https://github.com/xregistry/spec/assets/1944671/31bacb84-2904-4b93-bd23-20218d922c55">

**Comment by duglin** [comment]
Option 5:
<img width="326" alt="image" src="https://github.com/xregistry/spec/assets/1944671/a4e86f91-653c-4c99-b33c-4d56506d9c06">

**Comment by duglin** [comment]
Option 6:
<img width="338" alt="image" src="https://github.com/xregistry/spec/assets/1944671/d98a8f0e-2c7c-4f49-865c-eb528758b784">

**Comment by duglin** [comment]
Option 7:
<img width="331" alt="image" src="https://github.com/xregistry/spec/assets/1944671/41ec3bff-9d8e-45d2-bdaf-95cc2ac58781">

**Comment by duglin** [comment]
Option 8:
<img width="468" alt="image" src="https://github.com/xregistry/spec/assets/1944671/bce3f5be-40e5-4870-9c99-9673a3695978">

**Comment by duglin** [comment]
Option 9:
<img width="468" alt="image" src="https://github.com/xregistry/spec/assets/1944671/477d15cd-baf3-4f03-9290-7c2bd278dd5e">

**Comment by duglin** [comment]
Option 10:
<img width="468" alt="image" src="https://github.com/xregistry/spec/assets/1944671/ba76f804-4599-4cea-873b-54216b61f6b3">

**Comment by duglin** [comment]
There seems to be some interest in Option 10, so I'm asking for what that one might look like with the "X" in lowercase and with and w/o the blue box, so people can see those variants. I think the lowercase "x" might be important since that's what we decided on for it's name, and I'm not sure if the "blue box" make sense. Thoughts? I'm kind of assuming that the main think about 10 that's of interest is the cool looking font, but perhaps I'm wrong.

**Comment by duglin** [comment]
BTW we can still have a smaller logo:
<img width="152" alt="image" src="https://github.com/xregistry/spec/assets/1944671/da86a5d5-3e90-412a-a07e-878d219d11cc">
along with the longer one. In fact we probably should so it can be used where a square logo is needed - like a favicon. Do people have any opinion on this square logo? I kind of like it as is.

**Comment by tomkerkhove** [comment]
I like it as well!

**Comment by duglin** [comment]
xRegistry logos/icons can now be found here: https://github.com/cncf/artwork/tree/main/projects/xregistry
